# Generated by Django 4.0.4 on 2022-05-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_alter_meetup_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='organizer_email',
        ),
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2022-05-12'),
            preserve_default=False,
        ),
    ]
