# Generated by Django 4.0.4 on 2022-05-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_remove_meetup_organizer_email_meetup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='2022-05-13', max_length=254),
            preserve_default=False,
        ),
    ]
